In [22]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [23]:
df = pd.read_csv("Hyderabad.csv")
df

,Price,Area,Location,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,JoggingTrack,...,LiftAvailable,BED,VaastuCompliant,Microwave,GolfCourse,TV,DiningTable,Sofa,Wardrobe,Stadium
0,6968000,1340,Nizampet,2,0,0,1,1,1,1,...,1,0,1,0,0,0,0,0,0,0
1,29000000,3498,Hitech City,4,0,0,1,1,1,1,...,1,0,1,0,0,0,0,0,0,0
2,6590000,1318,Manikonda,2,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5739000,1295,Alwal,3,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,5679000,1145,Kukatpally,2,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2513,11000000,1460,Nacharam,2,1,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
2514,26000000,1314,Manikonda,2,1,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
2515,13300000,2625,Madhapur,3,1,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
2516,10800000,2050,Hitech City,3,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
2517,10400000,1805,Narsingi,3,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9

In [24]:
df.shape

(2518, 40)

In [25]:
df = df.drop_duplicates()

In [26]:
df.shape

(1998, 40)

In [27]:
df.isnull().sum()

Price                  0
Area                   0
Location               0
No. of Bedrooms        0
Resale                 0
MaintenanceStaff       0
Gymnasium              0
SwimmingPool           0
LandscapedGardens      0
JoggingTrack           0
RainWaterHarvesting    0
IndoorGames            0
ShoppingMall           0
Intercom               0
SportsFacility         0
ATM                    0
ClubHouse              0
School                 0
24X7Security           0
PowerBackup            0
CarParking             0
StaffQuarter           0
Cafeteria              0
MultipurposeRoom       0
Hospital               0
WashingMachine         0
Gasconnection          0
AC                     0
Wifi                   0
Children'splayarea     0
LiftAvailable          0
BED                    0
VaastuCompliant        0
Microwave              0
GolfCourse             0
TV                     0
DiningTable            0
Sofa                   0
Wardrobe               0
Stadium                0
dtype: int64

In [28]:
df['Location'] = LabelEncoder().fit_transform(df['Location'])

C:\Users\Zinkal Patel\AppData\Local\Temp\ipykernel_30544\4176234621.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Location'] = LabelEncoder().fit_transform(df['Location'])

In [29]:
df.head()

,Price,Area,Location,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,JoggingTrack,...,LiftAvailable,BED,VaastuCompliant,Microwave,GolfCourse,TV,DiningTable,Sofa,Wardrobe,Stadium
0,6968000,1340,162,2,0,0,1,1,1,1,...,1,0,1,0,0,0,0,0,0,0
1,29000000,3498,85,4,0,0,1,1,1,1,...,1,0,1,0,0,0,0,0,0,0
2,6590000,1318,132,2,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5739000,1295,9,3,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,5679000,1145,118,2,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0

In [30]:
X = df.drop('Price', axis=1)
y = df['Price']

In [31]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2, random_state=42)

In [32]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(Xtrain)
X_test_scaled = scaler.transform(Xtest)

In [33]:
models = {
    "Simple Linear Regression": LinearRegression(),
    "Multiple Linear Regression": LinearRegression(),
    "Multiple Linear Regression with PCA": Pipeline([
            ('pca', PCA(n_components=10)),
           ('lr', LinearRegression())]),
    "Lasso Regression": Lasso(alpha=1.0),
    "Ridge Regression": Ridge(alpha=1.0),
    "SVR": SVR(kernel='rbf', C=100, gamma=0.1, epsilon=.1),
    "Decision Tree": DecisionTreeRegressor(max_depth=5, random_state=42),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42)
}

In [46]:
results =[]
for name, model in models.items():
    if name == "Simple Linear Regression":
        model.fit(X_train_scaled[:, 0].reshape(-1, 1), ytrain)
        ypred = model.predict(X_test_scaled[:, 0].reshape(-1, 1))
    else:
        model.fit(X_train_scaled, ytrain)
        ypred = model.predict(X_test_scaled)
    print(f"MAE for {model}: {mae:.2f}")
    print(f"MSE for {model}: {mse:.2f}")
    print(f"RMSE for {model}: {rmse:.2f}")
    print(f"R² score for {name}: {r2:.4f}")
    print("-" * 30)

MAE for LinearRegression(): 1770815.82
MSE for LinearRegression(): 11958370457918.30
RMSE for LinearRegression(): 3458087.69
R² score for Simple Linear Regression: 0.7989
------------------------------
MAE for LinearRegression(): 1770815.82
MSE for LinearRegression(): 11958370457918.30
RMSE for LinearRegression(): 3458087.69
R² score for Multiple Linear Regression: 0.7989
------------------------------
MAE for Pipeline(steps=[('pca', PCA(n_components=10)), ('lr', LinearRegression())]): 1770815.82
MSE for Pipeline(steps=[('pca', PCA(n_components=10)), ('lr', LinearRegression())]): 11958370457918.30
RMSE for Pipeline(steps=[('pca', PCA(n_components=10)), ('lr', LinearRegression())]): 3458087.69
R² score for Multiple Linear Regression with PCA: 0.7989
------------------------------
MAE for Lasso(): 1770815.82
MSE for Lasso(): 11958370457918.30
RMSE for Lasso(): 3458087.69
R² score for Lasso Regression: 0.7989
------------------------------
MAE for Ridge(): 1770815.82
MSE for Ridge(): 11958370457918.30
RMSE for Ridge(): 3458087.69
R² score for Ridge Regression: 0.7989
------------------------------

D:\ANACONDA\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.340e+16, tolerance: 1.458e+13
  model = cd_fast.enet_coordinate_descent(

MAE for SVR(C=100, gamma=0.1): 1770815.82
MSE for SVR(C=100, gamma=0.1): 11958370457918.30
RMSE for SVR(C=100, gamma=0.1): 3458087.69
R² score for SVR: 0.7989
------------------------------
MAE for DecisionTreeRegressor(max_depth=5, random_state=42): 1770815.82
MSE for DecisionTreeRegressor(max_depth=5, random_state=42): 11958370457918.30
RMSE for DecisionTreeRegressor(max_depth=5, random_state=42): 3458087.69
R² score for Decision Tree: 0.7989
------------------------------
MAE for RandomForestRegressor(random_state=42): 1770815.82
MSE for RandomForestRegressor(random_state=42): 11958370457918.30
RMSE for RandomForestRegressor(random_state=42): 3458087.69
R² score for Random Forest: 0.7989
------------------------------